language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt

script:
  - sh make_migrations.sh
  - sh migrate.sh
  - sh run_tests.sh