language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE test;" -U postgres
  - psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres
script:
  - sh make_migrations.sh
  - sh migrate.sh
  - sh run_tests.sh